const AVAILABLE_CITIES = [
    { label: "BANJARNEGARA", value: "BANJARNEGARA" },
    { label: "BANYUMAS", value: "BANYUMAS" },
    { label: "BATANG", value: "BATANG" },
    { label: "BLORA", value: "BLORA" },
    { label: "BOYOLALI", value: "BOYOLALI" },
    { label: "BREBES", value: "BREBES" },
    { label: "CILACAP", value: "CILACAP" },
    { label: "DEMAK", value: "DEMAK" },
    { label: "GROBOGAN", value: "GROBOGAN" },
    { label: "JEPARA", value: "JEPARA" },
    { label: "KARANGANYAR", value: "KARANGANYAR" },
    { label: "KEBUMEN", value: "KEBUMEN" },
    { label: "KENDAL", value: "KENDAL" },
    { label: "KLATEN", value: "KLATEN" },
    { label: "KUDUS", value: "KUDUS" },
    { label: "MAGELANG", value: "MAGELANG" },
    { label: "PATI", value: "PATI" },
    { label: "PEKALONGAN", value: "PEKALONGAN" },
    { label: "PEMALANG", value: "PEMALANG" },
    { label: "PURBALINGGA", value: "PURBALINGGA" },
    { label: "PURWOREJO", value: "PURWOREJO" },
    { label: "REMBANG", value: "REMBANG" },
    { label: "SEMARANG", value: "SEMARANG" },
    { label: "SRAGEN", value: "SRAGEN" },
    { label: "SUKOHARJO", value: "SUKOHARJO" },
    { label: "TEGAL", value: "TEGAL" },
    { label: "TEMANGGUNG", value: "TEMANGGUNG" },
    { label: "WONOGIRI", value: "WONOGIRI" },
    { label: "WONOSOBO", value: "WONOSOBO" },
    { label: "MAGELANG", value: "MAGELANG" },
    { label: "PEKALONGAN", value: "PEKALONGAN" },
    { label: "SALATIGA", value: "SALATIGA" },
    { label: "SEMARANG", value: "SEMARANG" },
    { label: "SURAKARTA", value: "SURAKARTA" },
    { label: "TEGAL", value: "TEGAL" },
];

export default AVAILABLE_CITIES;
