const AVAILABLE_CITIES = [
    { label: "Banjarnegara", value: "BANJARNEGARA" },
    { label: "Banyumas", value: "BANYUMAS" },
    { label: "Batang", value: "BATANG" },
    { label: "Blora", value: "BLORA" },
    { label: "Boyolali", value: "BOYOLALI" },
    { label: "Brebes", value: "BREBES" },
    { label: "Cilacap", value: "CILACAP" },
    { label: "Demak", value: "DEMAK" },
    { label: "Grobogan", value: "GROBOGAN" },
    { label: "Jepara", value: "JEPARA" },
    { label: "Karanganyar", value: "KARANGANYAR" },
    { label: "Kebumen", value: "KEBUMEN" },
    { label: "Kendal", value: "KENDAL" },
    { label: "Klaten", value: "KLATEN" },
    { label: "Kudus", value: "KUDUS" },
    { label: "Pati", value: "PATI" },
    { label: "Pemalang", value: "PEMALANG" },
    { label: "Purbalingga", value: "PURBALINGGA" },
    { label: "Purworejo", value: "PURWOREJO" },
    { label: "Rembang", value: "REMBANG" },
    { label: "Semarang", value: "SEMARANG" },
    { label: "Sragen", value: "SRAGEN" },
    { label: "Sukoharjo", value: "SUKOHARJO" },
    { label: "Temanggung", value: "TEMANGGUNG" },
    { label: "Wonogiri", value: "WONOGIRI" },
    { label: "Wonosobo", value: "WONOSOBO" },
    { label: "Magelang", value: "MAGELANG" },
    { label: "Pekalongan", value: "PEKALONGAN" },
    { label: "Salatiga", value: "SALATIGA" },
    { label: "Surakarta", value: "SURAKARTA" },
    { label: "Tegal", value: "TEGAL" },
];

export default AVAILABLE_CITIES;
